title: Researcher
url: "https://alexdavidson.me"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no


sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Github"
   link: "https://github.com/adavidson1995"
 - name: "CV"
   link: "cv.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Blog"
   link: "/blog"

favicon: true
favicon_location: /assets/images/favicon.png
